/* ccode.c generated by valac 0.56.13, the Vala compiler
 * generated from ccode.vala, do not modify */

#include <stdlib.h>
#include <string.h>
#include <glib.h>

void terminal_write (const gchar* data);

